export type CourseOutlineRow = {
  sn: number;
  code: string;
  title: string;
  creditHours: number;
  /** GER | DER | MAJOR | ELECTIVE | MINOR, etc. */
  section: string;
  prerequisite?: string;
  /** e.g. "Year 1 · Semester I" — used to group study-plan rows */
  term?: string;
};

export type CourseOutlineElective = {
  sn: number;
  code: string;
  title: string;
  creditHours?: number;
};

export type CourseOutline = {
  slug: string;
  title: string;
  university: string;
  school: string;
  programme: string;
  tableHeading: string;
  summary: string;
  courses: CourseOutlineRow[];
  electives?: CourseOutlineElective[];
  notes?: string[];
};

export const COURSE_OUTLINES: CourseOutline[] = [
  {
    slug: 'computer-science-minor',
    title: 'Computer Science Minor Requirements',
    university: 'The University of The Gambia',
    school: 'School of Information Technology and Communication (SITC)',
    programme: 'Computer Science Minor',
    tableHeading: 'Computer Science Minor Core Courses',
    summary:
      'Students wishing to graduate from the University of The Gambia with a minor in Computer Science must complete a minimum of 120 credit hours including: All General Education Requirements of the University of The Gambia. All 57 credit hours of the 18 Computer Science core courses as defined below.',
    courses: [
      {
        sn: 1,
        code: 'ICT 101',
        title: 'Introduction to I.C.T.',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 2,
        code: 'ICT 105',
        title: 'Computer Programming I',
        creditHours: 4,
        section: 'MINOR',
      },
      {
        sn: 3,
        code: 'ICT 201',
        title: 'Computer Architecture & Organization',
        creditHours: 4,
        section: 'MINOR',
      },
      {
        sn: 4,
        code: 'ICT 202',
        title: 'Computer Programming II',
        creditHours: 4,
        section: 'MINOR',
      },
      {
        sn: 5,
        code: 'ICT 203',
        title: 'Computer Networking I',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 6,
        code: 'ICT 204',
        title: 'Database Systems I',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 7,
        code: 'ICT 205',
        title: 'Data Structure & Algorithms',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 8,
        code: 'ICT 206',
        title: 'Principles of Operating System',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 9,
        code: 'CPS 302',
        title: 'Internet and Web Programming I',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 10,
        code: 'CPS 305',
        title: 'Computer Logic and Discrete Structures',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 11,
        code: 'CPS 306',
        title: 'Automata and Languages',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 12,
        code: 'CPS 403',
        title: 'Artificial Intelligence',
        creditHours: 3,
        section: 'MINOR',
      },
    ],
  },
  {
    slug: 'information-systems-minor',
    title: 'Information Systems Minor Requirements',
    university: 'The University of The Gambia',
    school: 'School of Information Technology and Communication (SITC)',
    programme: 'Information Systems Minor',
    tableHeading: 'Information Systems Minor Courses',
    summary:
      'Students wishing to graduate from the University of The Gambia with a minor in Information Systems must complete a minimum of 12 Minor courses as defined below.',
    courses: [
      {
        sn: 1,
        code: 'ICT 102',
        title: 'Introduction to Computing & I.S',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 2,
        code: 'ICT 103',
        title: 'Programming Logic and Design',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 3,
        code: 'ICT 106',
        title: 'Ethics for Computing and Engineering',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 4,
        code: 'ICT 301',
        title: 'Project Management',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 5,
        code: 'INS 302',
        title: 'Systems Analysis & Design',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 6,
        code: 'ICT 204',
        title: 'Database Systems I',
        creditHours: 4,
        section: 'MINOR',
      },
      {
        sn: 7,
        code: 'INS 304',
        title: 'Service Centric and Cloud Computing',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 8,
        code: 'INS 305',
        title: 'Systems Administration and Security',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 9,
        code: 'INS 308',
        title: 'Internetworking & TCP/IP',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 10,
        code: 'INS 402',
        title: 'Access Control Sys. & Methodology',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 11,
        code: 'INS 414',
        title: 'Information Security & Auditing',
        creditHours: 3,
        section: 'MINOR',
      },
      {
        sn: 12,
        code: 'INS 405',
        title: 'Computer Forensics',
        creditHours: 3,
        section: 'MINOR',
      },
    ],
  },
  {
    slug: 'bsc-computer-science',
    title: 'BSc. (Hons) Computer Science Study Plan',
    university: 'The University of The Gambia',
    school: 'School of Information Technology and Communication (SITC)',
    programme: 'BSc. (Hons) Computer Science',
    tableHeading: 'Four-Year Study Plan',
    summary:
      'Official study plan for the Bachelor of Science (Honours) in Computer Science at the School of Information Technology and Communication (SITC). Courses are listed by year and semester with credit hours, prerequisites, and requirement category (GER, DER, MAJOR, or ELECTIVE). Students choose two 400-level electives in Year 4 Semester II from the elective list below.',
    courses: [
      {
        sn: 1,
        code: 'GEL 101',
        title: 'Use of English I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 2,
        code: 'MTH 101',
        title: 'Calculus I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 3,
        code: 'ICT 101',
        title: 'Introduction to I.C.T.',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 4,
        code: 'ICT 102',
        title: 'Introduction to Computing & I.S',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 5,
        code: 'ICT 103',
        title: 'Programming Logic and Design',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 6,
        code: 'ICT 104',
        title: 'Ethics for Computing and Engineering',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 7,
        code: 'GEL 102',
        title: 'Use of English 102',
        creditHours: 3,
        prerequisite: 'GEL 101',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 8,
        code: 'SCI 101',
        title: 'Introduction to General Science',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 9,
        code: 'MTH 102',
        title: 'Calculus II',
        creditHours: 3,
        prerequisite: 'MTH 101',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 10,
        code: 'GER 107',
        title: 'Cultural Studies',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 11,
        code: '—',
        title: 'Social and Behavioral Sciences (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 12,
        code: 'ICT 110',
        title: 'Computer Programming I',
        creditHours: 4,
        prerequisite: 'ICT 103',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 13,
        code: 'FRE 101',
        title: 'Elementary French I or any Foreign',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 14,
        code: 'PHY 101',
        title: 'Fundamentals of Physics I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 15,
        code: 'ICT 201',
        title: 'Computer Architecture & Organization',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 16,
        code: 'ICT 202',
        title: 'Computer Programming II',
        creditHours: 4,
        prerequisite: 'ICT 110',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 17,
        code: 'ICT 203',
        title: 'Computer Networking I',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 18,
        code: 'ICT 204',
        title: 'Database Systems I',
        creditHours: 4,
        prerequisite: 'ICT 102',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 19,
        code: 'FRE 102',
        title: 'Elementary French II or any Foreign',
        creditHours: 3,
        prerequisite: 'FRE 101',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 20,
        code: '—',
        title: 'Social and Behavioral Sciences (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 21,
        code: '—',
        title: 'Humanistic Tradition (Choose 1 Outside Major)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 22,
        code: 'MTH 203',
        title: 'Linear Algebra for Computer Science',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 23,
        code: 'ICT 210',
        title: 'Data Structure & Algorithms',
        creditHours: 4,
        prerequisite: 'ICT 202',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 24,
        code: 'ICT 211',
        title: 'Introduction to Operating Systems',
        creditHours: 3,
        prerequisite: 'ICT 202',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 25,
        code: '—',
        title: 'Economics & Mgt. Tradition (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 26,
        code: 'ICT 301',
        title: 'IT Project Management',
        creditHours: 3,
        prerequisite: 'ICT 103',
        section: 'DER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 27,
        code: 'CPS 301',
        title: 'Microprocessor Principles',
        creditHours: 3,
        prerequisite: 'ICT 201',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 28,
        code: 'CPS 302',
        title: 'Automata and Languages',
        creditHours: 3,
        prerequisite: 'None',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 29,
        code: 'CPS 303',
        title: 'Internet and Web Programming I',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 30,
        code: 'CPS 304',
        title: 'Operating Systems II',
        creditHours: 3,
        prerequisite: 'ICT 211',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 31,
        code: 'CPS 310',
        title: 'Internet and Web Programming II',
        creditHours: 3,
        prerequisite: 'CPS 302',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 32,
        code: 'CPS 311',
        title: 'Computer Logic and Discrete Structures',
        creditHours: 3,
        prerequisite: 'MTH 102',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 33,
        code: 'CPS 312',
        title: 'Object Oriented Analysis and Design',
        creditHours: 3,
        prerequisite: 'ICT 202',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 34,
        code: 'CPS 313',
        title: 'Computational Mathematics',
        creditHours: 3,
        prerequisite: 'MTH 101',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 35,
        code: 'CPS 314',
        title: 'Organization of Programming languages',
        creditHours: 3,
        prerequisite: 'ICT 210',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 36,
        code: 'ICT 315',
        title: 'Research Methodology in IT',
        creditHours: 3,
        prerequisite: 'None',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 37,
        code: 'CPS 401',
        title: 'Parallel and Distributed Programming',
        creditHours: 3,
        prerequisite: 'ICT 211',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 38,
        code: 'CPS 402',
        title: 'Artificial Intelligence',
        creditHours: 3,
        prerequisite: 'ICT 210',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 39,
        code: 'CPS 403',
        title: 'Cloud Computing',
        creditHours: 3,
        prerequisite: 'CPS 312',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 40,
        code: 'CPS 404',
        title: 'Data Communications and Networks',
        creditHours: 3,
        prerequisite: 'ICT 211',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 41,
        code: 'CPS 405',
        title: 'Database Systems II',
        creditHours: 3,
        prerequisite: 'ICT 204',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 42,
        code: 'ICT 406',
        title: 'Seminar',
        creditHours: 3,
        prerequisite: 'ICT 315',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 43,
        code: 'CPS 410',
        title: 'Compiler Design and Interpreters',
        creditHours: 3,
        prerequisite: 'CPS 301',
        section: 'MAJOR',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 44,
        code: 'CPS 419',
        title: 'Final Year Project',
        creditHours: 6,
        prerequisite: 'ICT 315',
        section: 'MAJOR',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 45,
        code: '400 Level',
        title: 'Electives',
        creditHours: 3,
        prerequisite: '—',
        section: 'ELECTIVE',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 46,
        code: '400 Level',
        title: 'Electives',
        creditHours: 3,
        prerequisite: '—',
        section: 'ELECTIVE',
        term: 'Year 4 · Semester II',
      },
    ],
    electives: [
      { sn: 1, code: 'CPS 411', title: 'LAN Administration', creditHours: 3 },
      { sn: 2, code: 'CPS 412', title: 'Advance Application Development', creditHours: 3 },
      {
        sn: 3,
        code: 'CPS 413',
        title: 'Object-Oriented Analysis and Design II',
        creditHours: 3,
      },
      { sn: 4, code: 'CPS 414', title: 'Analysis and design of Algorithms', creditHours: 3 },
      { sn: 5, code: 'CPS 415', title: 'Intelligent Systems', creditHours: 3 },
      {
        sn: 6,
        code: 'CPS 416',
        title: 'Information Security and Ethical Hacking',
        creditHours: 3,
      },
      { sn: 7, code: 'CPS 417', title: 'Big Data Analytics', creditHours: 3 },
      { sn: 8, code: 'CPS 418', title: 'Computer Networking II', creditHours: 3 },
    ],
  },
  {
    slug: 'bsc-telecommunication',
    title: 'BSc Telecommunication Study Plan',
    university: 'The University of The Gambia',
    school: 'School of Information Technology and Communication (SITC)',
    programme: 'BSc Telecommunication',
    tableHeading: 'Four-Year Study Plan',
    summary:
      'Official study plan for the Bachelor of Science in Telecommunication at the School of Information Technology and Communication (SITC). Courses are listed by year and semester with credit hours, prerequisites, and requirement category (GER, DER, MAJOR, or ELECTIVE). Students choose two 400-level electives in Year 4 Semester II from the elective list below. GER totals 36 credit hours as defined by the University of The Gambia.',
    courses: [
      {
        sn: 1,
        code: 'GEL 101',
        title: 'Use of English I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 2,
        code: 'MTH 101',
        title: 'Calculus I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 3,
        code: 'ICT 101',
        title: 'Introduction to I.C.T.',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 4,
        code: 'ICT 102',
        title: 'Introduction to Computing & I.S',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 5,
        code: 'ICT 103',
        title: 'Programming Logic and Design',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 6,
        code: 'ICT 104',
        title: 'Ethics for Computing and Engineering',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 7,
        code: 'GEL 102',
        title: 'Use of English 102',
        creditHours: 3,
        prerequisite: 'GEL 101',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 8,
        code: 'SCI 101',
        title: 'Introduction to General Science',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 9,
        code: 'MTH 102',
        title: 'Calculus II',
        creditHours: 3,
        prerequisite: 'MTH 101',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 10,
        code: 'GER 107',
        title: 'Cultural Studies',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 11,
        code: 'ICT 110',
        title: 'Computer Programming I',
        creditHours: 4,
        prerequisite: 'ICT 103',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 12,
        code: '—',
        title: 'Social and Behavioral Sciences (Choose any 1)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 13,
        code: 'FRE 101',
        title: 'Elementary French I or any Foreign Language',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 14,
        code: 'PHY 101',
        title: 'Fundamentals of Physics I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 15,
        code: 'ICT 201',
        title: 'Computer Architecture & Organization',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 16,
        code: 'ICT 202',
        title: 'Computer Programming II',
        creditHours: 3,
        prerequisite: 'ICT 110',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 17,
        code: 'ICT 203',
        title: 'Computer Networking I',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 18,
        code: 'ICT 204',
        title: 'Database Systems I',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 19,
        code: 'FRE 102',
        title: 'Elementary French II or any Foreign Language',
        creditHours: 3,
        prerequisite: 'FRE 101',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 20,
        code: '—',
        title: 'Social and Behavioral Sciences (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 21,
        code: '—',
        title: 'Humanistic Tradition (Choose 1 Outside Major)',
        creditHours: 4,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 22,
        code: 'MTH 203',
        title: 'Linear Algebra',
        creditHours: 3,
        prerequisite: 'MTH 102',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 23,
        code: 'ICT 210',
        title: 'Data Structure & Algorithms',
        creditHours: 3,
        prerequisite: 'ICT 202',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 24,
        code: 'ICT 211',
        title: 'Principles of Operating System',
        creditHours: 3,
        prerequisite: 'ICT 202',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 25,
        code: '—',
        title: 'Economics & Mgt. Tradition (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 26,
        code: 'MTH 301',
        title: 'Probability and Statistic I',
        creditHours: 3,
        prerequisite: 'MTH 102',
        section: 'GER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 27,
        code: 'ICT 301',
        title: 'Project Management',
        creditHours: 3,
        prerequisite: 'ICT 101',
        section: 'DER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 28,
        code: 'TEL 301',
        title: 'Analog and Digital Communications',
        creditHours: 3,
        prerequisite: 'ICT 101',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 29,
        code: 'TEL 302',
        title: 'Designing and Implementing Wi-Fi and VoIP Network',
        creditHours: 3,
        prerequisite: 'ICT 203',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 30,
        code: 'TEL 303',
        title: 'Designing and Administering Internetworks Infrastructure',
        creditHours: 3,
        prerequisite: 'ICT 203',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 31,
        code: 'TEL 310',
        title: 'Digital Systems',
        creditHours: 3,
        prerequisite: 'TEL 301',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 32,
        code: 'TEL 311',
        title: 'Switching and Automata Theory',
        creditHours: 3,
        prerequisite: 'TEL 301',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 33,
        code: 'TEL 312',
        title: 'Telecommunication Network Management',
        creditHours: 3,
        prerequisite: 'TEL 301',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 34,
        code: 'TEL 313',
        title: 'Satellite Technology',
        creditHours: 3,
        prerequisite: 'TEL 303',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 35,
        code: 'TEL 315',
        title: 'Fiber-Optic Communications',
        creditHours: 3,
        prerequisite: 'TEL 303',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 36,
        code: 'ICT 315',
        title: 'Research Methodology in IT',
        creditHours: 3,
        prerequisite: 'None',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 37,
        code: 'TEL 401',
        title: 'Mathematics for Engineers',
        creditHours: 3,
        prerequisite: 'TEL 301',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 38,
        code: 'TEL 402',
        title: 'Radio Frequency & Microwave Engineering',
        creditHours: 3,
        prerequisite: 'TEL 304',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 39,
        code: 'TEL 403',
        title: 'Mobile Computing & Wireless Networks',
        creditHours: 3,
        prerequisite: 'TEL 303',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 40,
        code: 'TEL 404',
        title: 'Digital Signal Processing',
        creditHours: 3,
        prerequisite: 'TEL 307',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 41,
        code: 'TEL 405',
        title: 'Telecommunication Quality of Service Audit',
        creditHours: 3,
        prerequisite: 'TEL 307',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 42,
        code: 'ICT 406',
        title: 'Seminar',
        creditHours: 3,
        prerequisite: 'ICT 315',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 43,
        code: 'TEL 407',
        title: 'Legal and Regulatory Issues in Telecommunications',
        creditHours: 3,
        prerequisite: 'None',
        section: 'MAJOR',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 44,
        code: 'ICT 408',
        title: 'Final Project',
        creditHours: 6,
        prerequisite: 'ICT 406',
        section: 'MAJOR',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 45,
        code: '400 Level',
        title: 'Elective',
        creditHours: 3,
        prerequisite: '—',
        section: 'ELECTIVE',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 46,
        code: '400 Level',
        title: 'Elective',
        creditHours: 3,
        prerequisite: '—',
        section: 'ELECTIVE',
        term: 'Year 4 · Semester II',
      },
    ],
    electives: [
      { sn: 1, code: 'TEL 409', title: 'Telecommunications Technology' },
      { sn: 2, code: 'TEL 410', title: 'Telecommunications Switching and Transmission' },
      { sn: 3, code: 'TEL 411', title: 'Broadband and Advance Communication' },
      { sn: 4, code: 'TEL 412', title: 'Sensor Networks and Intelligent Systems' },
      { sn: 5, code: 'TEL 413', title: 'Internet of Things' },
      { sn: 6, code: 'TEL 414', title: 'Radio Access Technologies' },
      { sn: 7, code: 'TEL 415', title: 'Mobile Computing' },
      { sn: 8, code: 'TEL 416', title: 'Computer Systems and Networks' },
    ],
    notes: [
      'GER — General Education Requirements [36 credit hours].',
      'Writing competence: GEL 101 Use of English 1 and GEL 102 Use of English 2 (6 semester hours).',
      'Mathematics competence: MTH 103 Basic Mathematics or MTH 101 Calculus 1 for all science students (3 semester hours).',
      'Information Technology competence: CPS 111 Introduction to Information Communication Technology (ICT) (3 semester hours).',
      'Foreign Language competence: Any language offered except English — FRE 101 & FRE 102, ARB 101 & ARB 102, or SPA 101 & SPA 102 (6 semester hours). Students doing a Major/Minor in French or Islamic Studies should do FRE 103 & FRE 104 or ARB 103 & ARB 104 respectively.',
      'Humanistic Tradition: GER 107 Cultural Studies plus one other course outside the student’s major area in History, Literature, Philosophy, Law, or Religious Studies (6 semester hours).',
      'Social and Behavioural Sciences: Two courses in Psychology, Anthropology, Geography, Political Science, Sociology, or Development and Gender Issues (6 semester hours).',
      'General Science competence: SCI 101 Introduction to General Science (3 semester hours).',
      'Economics and Management Tradition: MGT 100 Introduction to Management or ECO 200 Economics of Development (3 semester hours).',
    ],
  },
  {
    slug: 'bsc-information-systems',
    title: 'BSc. (Hons) Information Systems Study Plan',
    university: 'The University of The Gambia',
    school: 'School of Information Technology and Communication (SITC)',
    programme: 'BSc. (Hons) Information Systems',
    tableHeading: 'Four-Year Study Plan',
    summary:
      'Official study plan for the Bachelor of Science (Honours) in Information Systems at the School of Information Technology and Communication (SITC). Courses are listed by year and semester with credit hours, prerequisites, and requirement category (GER, DER, MAJOR, or ELECTIVE). Students choose two 400-level electives in Year 4 Semester II from the elective list below. GER totals 36 credit hours as defined by the University of The Gambia.',
    courses: [
      {
        sn: 1,
        code: 'GEL 101',
        title: 'Use of English I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 2,
        code: 'MTH 101',
        title: 'Calculus I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 3,
        code: 'ICT 101',
        title: 'Introduction to I.C.T.',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 4,
        code: 'ICT 102',
        title: 'Introduction to Computing & I.S',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 5,
        code: 'ICT 103',
        title: 'Programming Logic and Design',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 6,
        code: 'ICT 104',
        title: 'Ethics for Computing and Engineering',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 1 · Semester I',
      },
      {
        sn: 7,
        code: 'GEL 102',
        title: 'Use of English 102',
        creditHours: 3,
        prerequisite: 'GEL 101',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 8,
        code: 'SCI 101',
        title: 'Introduction to General Science',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 9,
        code: 'GER 107',
        title: 'Cultural Studies',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 10,
        code: 'MTH 102',
        title: 'Calculus II',
        creditHours: 3,
        prerequisite: 'MTH 101',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 11,
        code: 'ICT 110',
        title: 'Computer Programming I',
        creditHours: 4,
        prerequisite: 'ICT 103',
        section: 'DER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 12,
        code: '—',
        title: 'Social and Behavioral Sciences (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 1 · Semester II',
      },
      {
        sn: 13,
        code: 'FRE 101',
        title: 'Elementary French I or any Foreign',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 14,
        code: 'PHY 101',
        title: 'Fundamentals of Physics I',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 15,
        code: 'ICT 201',
        title: 'Computer Architecture & Organization',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 16,
        code: 'ICT 202',
        title: 'Computer Programming II',
        creditHours: 4,
        prerequisite: 'ICT 110',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 17,
        code: 'ICT 203',
        title: 'Computer Networking I',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 18,
        code: 'ICT 204',
        title: 'Database Systems I',
        creditHours: 4,
        prerequisite: 'ICT 102',
        section: 'DER',
        term: 'Year 2 · Semester I',
      },
      {
        sn: 19,
        code: 'FRE 102',
        title: 'Elementary French II or any Foreign',
        creditHours: 3,
        prerequisite: 'FRE 101',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 20,
        code: '—',
        title: 'Social and Behavioral Sciences (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 21,
        code: '—',
        title: 'Humanistic Tradition (Choose 1 Outside Major)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 22,
        code: 'ICT 210',
        title: 'Data Structure & Algorithms',
        creditHours: 4,
        prerequisite: 'ICT 202',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 23,
        code: 'ICT 211',
        title: 'Principles of Operating System',
        creditHours: 3,
        prerequisite: 'ICT 202',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 24,
        code: 'MTH 203',
        title: 'Linear Algebra',
        creditHours: 3,
        prerequisite: 'None',
        section: 'DER',
        term: 'Year 2 · Semester II',
      },
      {
        sn: 25,
        code: '—',
        title: 'Economics & Mgt. Tradition (Choose 1 Course)',
        creditHours: 3,
        prerequisite: 'None',
        section: 'GER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 26,
        code: 'ICT 301',
        title: 'Project Management',
        creditHours: 3,
        prerequisite: 'ICT 101',
        section: 'DER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 27,
        code: 'MTH 301',
        title: 'Probability and Statistics',
        creditHours: 3,
        prerequisite: 'MTH 102',
        section: 'DER',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 28,
        code: 'INS 301',
        title: 'Systems Analysis & Design',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 29,
        code: 'INS 302',
        title: 'Information Resource Management',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 30,
        code: 'INS 303',
        title: 'Data Engineering',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 31,
        code: 'INS 304',
        title: 'Systems Administration and Security',
        creditHours: 3,
        prerequisite: 'ICT 102',
        section: 'MAJOR',
        term: 'Year 3 · Semester I',
      },
      {
        sn: 32,
        code: 'INS 305',
        title: 'Access Control Sys. & Methodology',
        creditHours: 3,
        prerequisite: 'INS 304',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 33,
        code: 'INS 306',
        title: 'Service Centric and Cloud Computing',
        creditHours: 3,
        prerequisite: 'ICT 201',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 34,
        code: 'INS 307',
        title: 'E- Business for Development',
        creditHours: 3,
        prerequisite: 'INS 303',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 35,
        code: 'INS 308',
        title: 'Internetworking & TCP/IP',
        creditHours: 3,
        prerequisite: 'ICT 203',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 36,
        code: 'INS 309',
        title: 'Advanced Application Development',
        creditHours: 3,
        prerequisite: 'ICT 202',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 37,
        code: 'ICT 315',
        title: 'Research Methodology in IT',
        creditHours: 3,
        prerequisite: 'None',
        section: 'MAJOR',
        term: 'Year 3 · Semester II',
      },
      {
        sn: 38,
        code: 'INS 401',
        title: 'Business Continuity & Recovery Planning',
        creditHours: 3,
        prerequisite: 'INS 306',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 39,
        code: 'INS 402',
        title: 'Cross Platform & Enterprise Integration',
        creditHours: 3,
        prerequisite: 'INS 304',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 40,
        code: 'INS 403',
        title: 'Computer Forensics',
        creditHours: 3,
        prerequisite: 'INS 304',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 41,
        code: 'INS 404',
        title: 'Security Script Programming',
        creditHours: 3,
        prerequisite: 'INS 304',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 42,
        code: 'INS 405',
        title: 'Process Modelling & Solution Blueprint',
        creditHours: 3,
        prerequisite: 'ICT 301',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 43,
        code: 'ICT 406',
        title: 'Seminar',
        creditHours: 3,
        prerequisite: 'ICT 315',
        section: 'MAJOR',
        term: 'Year 4 · Semester I',
      },
      {
        sn: 44,
        code: 'INS 407',
        title: 'Information Security & Auditing',
        creditHours: 3,
        prerequisite: 'INS 304',
        section: 'MAJOR',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 45,
        code: 'ICT 408',
        title: 'Project',
        creditHours: 6,
        prerequisite: 'ICT 406',
        section: 'MAJOR',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 46,
        code: '400 Level',
        title: 'Electives',
        creditHours: 3,
        prerequisite: '—',
        section: 'ELECTIVE',
        term: 'Year 4 · Semester II',
      },
      {
        sn: 47,
        code: '400 Level',
        title: 'Electives',
        creditHours: 3,
        prerequisite: '—',
        section: 'ELECTIVE',
        term: 'Year 4 · Semester II',
      },
    ],
    electives: [
      {
        sn: 1,
        code: 'INS 409',
        title: 'Entrepreneurship (Strongly recommended)',
        creditHours: 3,
      },
      { sn: 2, code: 'INS 410', title: 'Foundations of Cryptography', creditHours: 3 },
      {
        sn: 3,
        code: 'INS 411',
        title: 'Management Process and Organization Behavior',
        creditHours: 3,
      },
      { sn: 4, code: 'INS 412', title: 'Introduction to Cyber Security', creditHours: 3 },
      { sn: 5, code: 'INS 413', title: 'Internet and Web Technologies', creditHours: 3 },
      {
        sn: 6,
        code: 'INS 414',
        title: 'Applications in Information Security and Assurance',
        creditHours: 3,
      },
      {
        sn: 7,
        code: 'INS 415',
        title: 'Policy and Administration in Information Security and Assurance',
        creditHours: 3,
      },
      {
        sn: 8,
        code: 'INS 416',
        title: 'UNIX System Administration & Security',
        creditHours: 3,
      },
      { sn: 9, code: 'INS 417', title: 'Human Computer Interaction', creditHours: 3 },
      { sn: 10, code: 'INS 418', title: 'Geographic Information Systems', creditHours: 3 },
    ],
    notes: [
      'GER — General Education Requirements [36 credit hours].',
      'Writing competence: GEL 101 Use of English 1 and GEL 102 Use of English 2 (6 semester hours).',
      'Mathematics competence: MTH 103 Basic Mathematics or MTH 101 Calculus 1 for all science students (3 semester hours).',
      'Information Technology competence: CPS 111 Introduction to Information Communication Technology (ICT) (3 semester hours).',
      'Foreign Language competence: Any language offered except English — FRE 101 & FRE 102, ARB 101 & ARB 102, or SPA 101 & SPA 102 (6 semester hours). Students doing a Major/Minor in French or Islamic Studies should do FRE 103 & FRE 104 or ARB 103 & ARB 104 respectively.',
      'Humanistic Tradition: GER 107 Cultural Studies plus one other course outside the student’s major area in History, Literature, Philosophy, Law, or Religious Studies (6 semester hours).',
      'Social and Behavioural Sciences: Two courses in Psychology, Anthropology, Geography, Political Science, Sociology, or Development and Gender Issues (6 semester hours).',
      'General Science competence: SCI 101 Introduction to General Science (3 semester hours).',
      'Economics and Management Tradition: MGT 100 Introduction to Management or ECO 200 Economics of Development (3 semester hours).',
    ],
  },
];

export function getCourseOutline(slug: string) {
  return COURSE_OUTLINES.find((outline) => outline.slug === slug) ?? null;
}

export function totalCreditHours(outline: CourseOutline) {
  return outline.courses.reduce((sum, course) => sum + course.creditHours, 0);
}

/** Groups study-plan rows by term while preserving order. */
export function groupCoursesByTerm(courses: CourseOutlineRow[]) {
  const groups: { term: string | null; courses: CourseOutlineRow[] }[] = [];

  for (const course of courses) {
    const term = course.term ?? null;
    const last = groups[groups.length - 1];
    if (last && last.term === term) {
      last.courses.push(course);
    } else {
      groups.push({ term, courses: [course] });
    }
  }

  return groups;
}

export function outlineHasPrerequisites(outline: CourseOutline) {
  return outline.courses.some((course) => Boolean(course.prerequisite));
}

export function outlineMetaLabel(outline: CourseOutline) {
  const credits = totalCreditHours(outline);
  const hasTerms = outline.courses.some((course) => Boolean(course.term));
  if (hasTerms) {
    const termCount = new Set(outline.courses.map((c) => c.term).filter(Boolean)).size;
    const electiveCount = outline.electives?.length ?? 0;
    return `${termCount} terms · ${credits} credit hrs${
      electiveCount ? ` · ${electiveCount} electives` : ''
    }`;
  }
  return `${outline.courses.length} courses · ${credits} credit hrs listed`;
}
